name: Build and Deploy to Dev

on:
  push:
    branches: [ archima-warriors-cloudHub2.0 ]
  pull_request:
    branches: [ archima-warriors-cloudHub2.0 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4 

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
        PASSWORD: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
        Business_Group_Id: ${{ secrets.Business_Group_Id }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Dclient.id="$USERNAME" \
         -Dclient.secret="$PASSWORD" \
         -Danypoint.businessGroup="$Business_Group_Id" \
         -Danypoint.platform.client_id="$CLIENT_ID" \
         -Danypoint.platform.client_secret="$CLIENT_SECRET" \
         -Denv=Dev \
         -Dappname=deploy-cloudhub2
